// ============================================================================
// miningReference.ts — bundled mining reference data loader.
// ----------------------------------------------------------------------------
// LOCAL-FIRST, mirroring salvageReference.ts / uexClient.ts. The Mining mode
// needs static game reference data (mineable rock scan-signature values and the
// material -> location deposit map). It changes only per game patch, so instead
// of any runtime fetch we ship a BUNDLED SNAPSHOT and serve it directly. No
// network, no token.
//
//   • Snapshot: electron/data/mining-reference.json (generated by the dev
//               script scripts/fetch-mining-reference.mjs from two source CSVs
//               under electron/data/sources/ — see that script).
//   • Inlining: the JSON is `import`ed below so electron-vite/Vite inlines it
//               into the main bundle at build time (lives inside the asar).
//
// The data is purely game reference (rock/material names, scan values,
// locations) — it carries no personal data.
// ============================================================================

import type { MiningReferenceData } from "@shared/types";

// resolveJsonModule is enabled (tsconfig.node); electron-vite inlines this JSON.
import refData from "./data/mining-reference.json";

/** Shape of the bundled snapshot (a superset of MiningReferenceData). */
interface MiningReferenceSnapshot extends MiningReferenceData {
  fetchedAt: number;
  source: string;
}

const snapshot = refData as unknown as MiningReferenceSnapshot;

export interface MiningReferenceLoader {
  /** Return the bundled mining reference snapshot. No network, no token. */
  getReferenceData(): MiningReferenceData;
  /** True when the snapshot has usable data (always true for the bundled file). */
  isActive(): boolean;
}

export interface MiningReferenceOptions {
  /** Optional override for the bundled snapshot (tests). */
  snapshot?: MiningReferenceData;
}

class MiningReferenceImpl implements MiningReferenceLoader {
  private readonly data: MiningReferenceData;

  constructor(opts: MiningReferenceOptions = {}) {
    this.data = opts.snapshot ?? {
      rocks: snapshot.rocks,
      deposits: snapshot.deposits,
    };
  }

  getReferenceData(): MiningReferenceData {
    return this.data;
  }

  isActive(): boolean {
    return this.data.rocks.length > 0 || this.data.deposits.length > 0;
  }
}

/**
 * Construct the mining reference loader backed by the bundled snapshot. To
 * update it for a new game patch, replace the source CSVs under
 * electron/data/sources/ and run `npm run fetch:mining-reference` (dev-only).
 */
export function createMiningReference(
  options: MiningReferenceOptions = {},
): MiningReferenceLoader {
  return new MiningReferenceImpl(options);
}
