// ============================================================================
// salvageReference.ts — bundled salvage reference data loader.
// ----------------------------------------------------------------------------
// LOCAL-FIRST, mirroring uexClient.ts. The salvage tracker needs static game
// reference data (ship loadouts by cost tier, component sell prices, material
// rates, hauler grid sizes). It changes only per game patch, so instead of any
// runtime fetch we ship a BUNDLED SNAPSHOT and serve it directly. No network,
// no token.
//
//   • Snapshot: electron/data/salvage-reference.json (generated by the dev
//               script scripts/fetch-salvage-reference.py from a community
//               worksheet — see that file; the worksheet is never bundled).
//   • Inlining: the JSON is `import`ed below so electron-vite/Vite inlines it
//               into the main bundle at build time (lives inside the asar).
//
// The data is purely game reference (ship/component names + prices) — it carries
// no personal data.
// ============================================================================

import type { SalvageReferenceData } from "@shared/types";

// resolveJsonModule is enabled (tsconfig.node); electron-vite inlines this JSON.
import refData from "./data/salvage-reference.json";

/** Shape of the bundled snapshot (a superset of SalvageReferenceData). */
interface SalvageReferenceSnapshot extends SalvageReferenceData {
  fetchedAt: number;
  source: string;
}

const snapshot = refData as unknown as SalvageReferenceSnapshot;

export interface SalvageReferenceLoader {
  /** Return the bundled salvage reference snapshot. No network, no token. */
  getReferenceData(): SalvageReferenceData;
  /** True when the snapshot has usable data (always true for the bundled file). */
  isActive(): boolean;
}

export interface SalvageReferenceOptions {
  /** Optional override for the bundled snapshot (tests). */
  snapshot?: SalvageReferenceData;
}

class SalvageReferenceImpl implements SalvageReferenceLoader {
  private readonly data: SalvageReferenceData;

  constructor(opts: SalvageReferenceOptions = {}) {
    this.data = opts.snapshot ?? {
      ships: snapshot.ships,
      components: snapshot.components,
      materialPrices: snapshot.materialPrices,
      haulers: snapshot.haulers,
    };
  }

  getReferenceData(): SalvageReferenceData {
    return this.data;
  }

  isActive(): boolean {
    return (
      this.data.ships.length > 0 ||
      this.data.components.length > 0 ||
      this.data.haulers.length > 0
    );
  }
}

/**
 * Construct the salvage reference loader backed by the bundled snapshot. To
 * update it for a new game patch, run `npm run fetch:salvage-reference`
 * (dev-only; see scripts/fetch-salvage-reference.py).
 */
export function createSalvageReference(
  options: SalvageReferenceOptions = {},
): SalvageReferenceLoader {
  return new SalvageReferenceImpl(options);
}
