// ============================================================================
// uexClient.ts — bundled UEX reference data  (SPEC §2, §5 ReferenceCache)
// ----------------------------------------------------------------------------
// LOCAL-FIRST. The app needs UEX data only for manual-entry dropdowns + name
// normalization, and it changes only per game patch. So instead of querying the
// UEX API at runtime (Bearer token, sqlite cache, 24h TTL, startup refresh) we
// ship a BUNDLED SNAPSHOT and serve it directly. No network, no token, no TTL
// on the runtime path — and no token is shipped in the packaged app.
//
//   • Snapshot:  electron/data/reference-data.json (generated by the dev script
//                `npm run fetch:reference`, see scripts/fetch-reference.mjs).
//   • Inlining:  the JSON is `import`ed below so electron-vite/Vite inlines it
//                into out/main/index.js — guaranteeing it lives inside the asar
//                with no separate file to copy.
//
// The mapping helpers (mapCommodities/mapTerminals) stay exported: they are the
// shared normalization used by the dev fetch script (and exercised by tests).
//
// Public interface (createUexClient -> getReferenceData) is preserved so main.ts
// and the IPC contract (ref:get) do not change shape.
// ============================================================================

import type { ReferenceData, Commodity, Terminal } from "@shared/types";

// The bundled per-patch snapshot. resolveJsonModule is enabled (tsconfig.node),
// and electron-vite inlines the JSON into the main bundle at build time.
import refData from "./data/reference-data.json";

/** Shape of the bundled snapshot file (a superset of ReferenceData). */
interface ReferenceSnapshot {
  fetchedAt: number;
  source: string;
  commodities: Commodity[];
  terminals: Terminal[];
}

const snapshot = refData as ReferenceSnapshot;

// ---------------------------------------------------------------------------
// Normalization: raw UEX rows -> shared types.
// Still exported — reused by scripts/fetch-reference.mjs and the unit tests so
// the bundled snapshot and any future refresh produce identical, validated shapes.
// ---------------------------------------------------------------------------

interface RawUexResponse {
  data?: unknown;
}

function asArray(resp: unknown): unknown[] {
  // UEX wraps payloads as { status, data: [...] }. Accept a bare array too.
  if (Array.isArray(resp)) return resp;
  if (resp && typeof resp === "object") {
    const d = (resp as RawUexResponse).data;
    if (Array.isArray(d)) return d;
  }
  return [];
}

function str(v: unknown): string {
  return typeof v === "string" ? v : v == null ? "" : String(v);
}

function truthyFlag(v: unknown): boolean {
  // UEX flags come back as 1/0 (numbers) or occasionally booleans.
  return v === 1 || v === true || v === "1";
}

function numOrNull(v: unknown): number | null {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string" && v.trim() !== "" && !Number.isNaN(Number(v)))
    return Number(v);
  return null;
}

export function mapCommodities(resp: unknown): Commodity[] {
  return asArray(resp)
    .map((row) => {
      const r = row as Record<string, unknown>;
      return {
        name: str(r.name),
        code: str(r.code),
        kind: str(r.kind),
      };
    })
    .filter((c) => c.name.length > 0);
}

export function mapTerminals(resp: unknown): Terminal[] {
  return (
    asArray(resp)
      .map((row) => {
        const r = row as Record<string, unknown>;
        return {
          name: str(r.name),
          displayname: str(r.displayname),
          nickname: str(r.nickname),
          isCargoCenter: truthyFlag(r.is_cargo_center),
          maxContainerSize: numOrNull(r.max_container_size),
        };
      })
      .filter((t) => t.name.length > 0)
      // SPEC §2: dropdowns filter to cargo centers.
      .filter((t) => t.isCargoCenter)
  );
}

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

export interface UexClientOptions {
  /**
   * Optional override for the bundled snapshot (tests). When omitted the
   * inlined per-patch snapshot is used. No token, dbPath, TTL, or fetch any more.
   */
  snapshot?: ReferenceData;
}

export interface UexClient {
  /** Return the bundled reference snapshot. No network, no token, no TTL. */
  getReferenceData(): ReferenceData;
  /** Always true: the bundled snapshot is always available. */
  isActive(): boolean;
  /** No-op; retained for interface stability. */
  close(): void;
}

class UexClientImpl implements UexClient {
  private data: ReferenceData;

  constructor(opts: UexClientOptions = {}) {
    this.data = opts.snapshot ?? {
      commodities: snapshot.commodities,
      terminals: snapshot.terminals,
    };
  }

  getReferenceData(): ReferenceData {
    return this.data;
  }

  isActive(): boolean {
    // The bundled snapshot is always present, so reference data is always active.
    return this.data.commodities.length > 0;
  }

  close(): void {
    // No resources to release — the snapshot is just an in-memory object.
  }
}

/**
 * Construct a UEX client backed by the bundled per-patch snapshot. No network is
 * ever touched and no token is required. To update the snapshot for a new game
 * patch, run `npm run fetch:reference` (dev-only, see scripts/fetch-reference.mjs).
 */
export function createUexClient(options: UexClientOptions = {}): UexClient {
  return new UexClientImpl(options);
}
